name: msal_guard
description: Guard widget for the Msal Flutter library
version: 0.0.1-alpha.9
homepage: https://github.com/muljin/msal-guard
repository: https://github.com/muljin/msal-guard

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  # msal_flutter: 2.0.0-alpha.4
  msal_flutter:
    path: ../46-msal-flutter
  provider: ^5.0.0
  rxdart: ^0.26.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  