name: msal_guard
description: Guard widget for the Msal Flutter library
version: 0.0.2
homepage: https://github.com/muljin/msal-guard
repository: https://github.com/muljin/msal-guard
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.1 <1.0.0"
  msal_flutter: 2.0.0-beta.2
  provider: ">=5.0.0 <7.0.0"
  rxdart: ">=0.26.0 <1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.1
  build_runner:
flutter:
  